# Generated by Django 2.2.16 on 2020-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_orgs_repos_templates_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='3ayfAuVhFvKQL8x2mtyc5tXicfhPRg', max_length=100),
        ),
    ]
