# Generated by Django 2.2.16 on 2020-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_orgs_repos_templates_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='pGzp5K9Kqt4WLLg8GpGMumhpFraeCK', max_length=100),
        ),
    ]
