# Generated by Django 2.2.16 on 2020-10-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201012_2320'),
    ]

    operations = [
    ]
