# Generated by Django 2.2.16 on 2020-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201015_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='3fbkLqvhtSa88MgT3j6Cm6VVGQP934', max_length=100),
        ),
    ]
