# Generated by Django 2.2.16 on 2020-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20201015_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates_rendered', models.BigIntegerField(default=0)),
                ('templates_saved', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='rAeHAPb92y3NyCj8uwm5RVoToxWNaV', max_length=100),
        ),
    ]
