# Generated by Django 2.2.16 on 2020-10-13 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20201012_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='ewvBakWz58wn2QTxqFm2S66B3u3Fkw', max_length=100),
        ),
    ]
