# Generated by Django 2.2.16 on 2020-10-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20201013_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='restapi.Repos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='RxRebKKqZjAsiumgHLCBS9UoHcB3VS', max_length=100),
        ),
    ]
