# Generated by Django 2.2.16 on 2020-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20201013_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='3U2dSWaXq8SYYUzJyYmBhr2CYgzpjM', max_length=100),
        ),
    ]
