# Generated by Django 2.2.16 on 2020-10-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20201013_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='yWGGhfRmN5p4tK3RqiDk6yqZtyfir8', max_length=100),
        ),
    ]
