# Generated by Django 2.2.16 on 2020-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20201013_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='delete',
            new_name='purge',
        ),
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='FRVmKeG8jXdVSMxKdQ8b99xMhxQSNs', max_length=100),
        ),
    ]
